/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FAQ {
  'id' : FaqId,
  'question' : string,
  'displayOrder' : bigint,
  'answer' : string,
}
export type FaqId = bigint;
export interface Lead {
  'id' : LeadId,
  'purchaseDate' : Timestamp,
  'fullName' : string,
  'productId' : ProductId,
  'email' : string,
  'stripeSessionId' : string,
}
export type LeadId = bigint;
export interface Product {
  'id' : ProductId,
  'title' : string,
  'description' : string,
  'productType' : ProductType,
  'isActive' : boolean,
  'price' : bigint,
}
export type ProductId = bigint;
export type ProductType = { 'Playbook' : null } |
  { 'Guide' : null } |
  { 'Compendium' : null } |
  { 'Handbook' : null } |
  { 'Framework' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface SiteSettings { 'facebookPixelId' : string }
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createLead' : ActorMethod<[string, string, ProductId, string], Lead>,
  'deleteFAQ' : ActorMethod<[FaqId], boolean>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFAQs' : ActorMethod<[], Array<FAQ>>,
  'getLead' : ActorMethod<[LeadId], [] | [Lead]>,
  'getLeads' : ActorMethod<[], Array<Lead>>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getSiteSettings' : ActorMethod<[], SiteSettings>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateSiteSettings' : ActorMethod<[string], SiteSettings>,
  'upsertFAQ' : ActorMethod<[FAQ], FAQ>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];