/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const ProductId = IDL.Nat;
export const LeadId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Lead = IDL.Record({
  'id' : LeadId,
  'purchaseDate' : Timestamp,
  'fullName' : IDL.Text,
  'productId' : ProductId,
  'email' : IDL.Text,
  'stripeSessionId' : IDL.Text,
});
export const FaqId = IDL.Nat;
export const FAQ = IDL.Record({
  'id' : FaqId,
  'question' : IDL.Text,
  'displayOrder' : IDL.Nat,
  'answer' : IDL.Text,
});
export const ProductType = IDL.Variant({
  'Playbook' : IDL.Null,
  'Guide' : IDL.Null,
  'Compendium' : IDL.Null,
  'Handbook' : IDL.Null,
  'Framework' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'productType' : ProductType,
  'isActive' : IDL.Bool,
  'price' : IDL.Nat,
});
export const SiteSettings = IDL.Record({ 'facebookPixelId' : IDL.Text });
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createLead' : IDL.Func(
      [IDL.Text, IDL.Text, ProductId, IDL.Text],
      [Lead],
      [],
    ),
  'deleteFAQ' : IDL.Func([FaqId], [IDL.Bool], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFAQs' : IDL.Func([], [IDL.Vec(FAQ)], ['query']),
  'getLead' : IDL.Func([LeadId], [IDL.Opt(Lead)], ['query']),
  'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateSiteSettings' : IDL.Func([IDL.Text], [SiteSettings], []),
  'upsertFAQ' : IDL.Func([FAQ], [FAQ], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const ProductId = IDL.Nat;
  const LeadId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Lead = IDL.Record({
    'id' : LeadId,
    'purchaseDate' : Timestamp,
    'fullName' : IDL.Text,
    'productId' : ProductId,
    'email' : IDL.Text,
    'stripeSessionId' : IDL.Text,
  });
  const FaqId = IDL.Nat;
  const FAQ = IDL.Record({
    'id' : FaqId,
    'question' : IDL.Text,
    'displayOrder' : IDL.Nat,
    'answer' : IDL.Text,
  });
  const ProductType = IDL.Variant({
    'Playbook' : IDL.Null,
    'Guide' : IDL.Null,
    'Compendium' : IDL.Null,
    'Handbook' : IDL.Null,
    'Framework' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'productType' : ProductType,
    'isActive' : IDL.Bool,
    'price' : IDL.Nat,
  });
  const SiteSettings = IDL.Record({ 'facebookPixelId' : IDL.Text });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createLead' : IDL.Func(
        [IDL.Text, IDL.Text, ProductId, IDL.Text],
        [Lead],
        [],
      ),
    'deleteFAQ' : IDL.Func([FaqId], [IDL.Bool], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFAQs' : IDL.Func([], [IDL.Vec(FAQ)], ['query']),
    'getLead' : IDL.Func([LeadId], [IDL.Opt(Lead)], ['query']),
    'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateSiteSettings' : IDL.Func([IDL.Text], [SiteSettings], []),
    'upsertFAQ' : IDL.Func([FAQ], [FAQ], []),
  });
};

export const init = ({ IDL }) => { return []; };